language: R
cache: packages

r:
  - oldrel
  - release
  - devel

r_packages:
  - covr

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email: false
  slack:
    rooms:
      - poissonconsulting:BKjfn7jsVh8zXTu2rq7BEQEb
    on_success: change
    on_failure: always
